### ISSUE TITLE
Wisemonk should not accept negative values for meditation

### ISSUE THREAD

**Issue by ghoseb** [dgraph-io/wisemonk#2]
`time.ParseDuration` [accepts negative numbers](https://golang.org/pkg/time/#ParseDuration), so it'd be better to validate user input here: https://github.com/dgraph-io/wisemonk/blob/master/main.go#L363

Otherwise it could introduce a potential DOS vector by disallowing wisemonk to meditate :-)

**Comment by pawanrawal** [comment]
Thanks for reporting this @ghoseb. We will push in a fix soon.

**Comment by pawanrawal** [comment]
Fixed!
