### ISSUE TITLE
Docker image; are there plans?

### ISSUE THREAD

**Issue by modius** [dgraph-io/wisemonk#3]
Was wondering if you had any plans to publish a configurable docker image for **wisemonk**.

**Comment by pawanrawal** [comment]
Sure we could do that. That should be easy to setup. If anyone from the community is interested in doing this, feel free to take this up or else I will take it up.

**Comment by manishrjain** [comment]
Also, if we release a `wisemonk` binary, then the docker image shouldn't be necessary.
