### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by jwulf** [dgraph-io/wisemonk#6]
I've been trying to get this to work. I can build it and run it, but see no output. A Slackbot joins a channel, but that's it...

**Comment by benblaine** [comment]
I'm also trying to get this to work - would be really helpful in our Slack community!

I added `$GOPATH/bin` to path on mac and I ran but it says it's not installed...

```
$ go get github.com/dgraph-io/wisemonk
$ go install github.com/dgraph-io/wisemonk
$ wisemonk
-bash: wisemonk: command not found
```

**Comment by benblaine** [comment]
@jwulf if not this might work https://meta.discourse.org/t/chatroom-integration-plugin-discourse-chat-integration/66522 - see the title "Posting a transcript"

**Comment by jwulf** [comment]
I wrote this in the end: https://github.com/camunda-community-hub/slack-archivist
